# Список редиректов. По умолчанию: redirects: []
# Пример:
# redirects:
#   - host: domain1.com
#     path: /
#   - host: domain2.com
#     path: /lp/test
redirects: []


# Список зеркал. Параметр query - необязательный. По умолчанию: mirrors: []
mirrors:
  - host: xn--80aac8afrzi0cyb.xn--p1ai
    path: /trial_kids
    query: version=basta_trial_kids


